services:
  app:
    ports: !reset []
    networks:
      default: {}
      proxy:
        aliases:
          - f1-app
  caddy:
    networks:
      default: {}
      proxy: {}

networks:
  proxy:
    external: true
    name: proxy
